( Generated by VirTriad   )
( Pic 2 GCode for Grbl    )
( Start Point : LL        )
( Frame Mode  : Abs.      )
( Image Width : 50.0   mm )
(               500    px )
( Image Height: 44.1   mm )
(               441    px )
( X Maximum   : 75.0   mm )
( Y Maximum   : 44.1   mm )
( X Minimum   : -25.0  mm )
( Y Minimum   : 0.0    mm )
( X Overshoot : 25.0   mm )
( Laser Max   : 1000      )
( Feed Rate   : 2500      )
( Pixel Width : 0.1    mm )
( Resolution  : 0.1    mm )
( Image Name  : F:\Codez\testvm\gcode\test\fill_seed.png )
G21
G90
F2500
M05
M03 S0
G01 X-2.6 Y4.8 M03 S0
M03 S0
M05
G00 X0 Y0
